language: node_js
node_js:
  - 'lts/*'
  - 'node'
branches:
  only:
    - master
    - dev
script: npm run test && codecov
before_install:
- rm -rf node_modules
- npm install -g greenkeeper-lockfile codecov
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload